# Changer le .env.example => .env

services: 
  mysql:
    restart: always
    image: mysql
    env_file:
      - ./back-end/.env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data: